#!/usr/bin/env python3
"""Crop selection for multi-crop RL experiments.

This script is the canonical, reproducible source-of-truth for which crops
are used as ID (in-distribution) training crops and which are held out as
a fixed OOD (out-of-distribution) evaluation set.

Experimental design: Crop Diversity Scaling
-------------------------------------------
Core question: under a fixed training budget (3200 episodes), does
increasing trait diversity (more crops, fewer samples per crop) improve
OOD generalization?

    Condition   ID crops   samples/crop
    ─────────   ────────   ────────────
    4-ID        4          800
    8-ID        8          400
    16-ID       16         200

All three conditions share the **same fixed OOD eval set** (4 crops) so
that OOD performance is directly comparable across conditions.

Selection methodology
---------------------
1. Load structured crop-trait JSON cards (generated by build_crop_traits.py).
2. Exclude crops that cannot complete a 240-day episode (verified by
   check_crop_maturity.py across 12 location × year weather scenarios).
3. Normalise the selected trait vector for each crop.
4. **Select the OOD set first**: exhaustive search over C(20,4)=4845
   candidate OOD sets, scoring each by a weighted combination of
   (a) remaining ID pool trait-space volume and (b) OOD set spread.
5. From the remaining 16-crop ID pool:
   - 4-ID: exhaustive search for the 4-crop subset that maximises
     the minimum pairwise distance.
   - 8-ID: greedily expand the optimal 4 by adding the crop farthest
     from the current set (max-min diversification).
   - 16-ID: use the full ID pool.
6. Report coverage metrics and OOD distances.

Trait schemas
-------------
traits_v1_23d selection subspace (8 dimensions)
TBASEM        base temperature for emergence (°C)
TSUM_total    total thermal-time requirement (°C·d)
IDSL          development driver: temp-only(0) / +daylength(1) / +vernalization(2)
RDMCR         maximum rooting depth (cm)
DEPNR         drought tolerance proxy (higher = more tolerant)
AMAX          peak leaf CO₂ assimilation rate (kg ha⁻¹ hr⁻¹)
FOTB_onset    DVS at which storage-organ allocation begins
IAIRDU        air ducts in roots (0 or 1)

traits_v1_6d selection subspace (6 dimensions)
season_urgency
development_constraint
water_priority
nitrogen_priority
phosphorus_priority
potassium_priority

Usage
-----
    # Print selections and coverage analysis
    python integrations/wofost_gym/crop_pool_design/select_crops.py

    # Write one weather-pool YAML config per usable crop
    python integrations/wofost_gym/crop_pool_design/select_crops.py --write-per-crop-configs
"""

from __future__ import annotations

import argparse
import json
from itertools import combinations
from pathlib import Path
from typing import Any, Dict, List, Tuple

import numpy as np
import yaml

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_TRAITS_DIR = REPO_ROOT / "agrimanager" / "env" / "wofost_gym" / "crop_traits"
POOL_CONFIG_DIR = REPO_ROOT / "integrations" / "wofost_gym" / "dataset_tools" / "weather_pool_configs"

# ---------------------------------------------------------------------------
# Exclusions — crops that cannot run a 240-day episode
# ---------------------------------------------------------------------------
# Verified by check_crop_maturity.py across 12 location × year scenarios.
EXCLUDED_CROPS = {
    "grape":     "FOTB_onset is None (perennial, no annual storage-organ cycle)",
    "tobacco":   "DVS stays at -0.10 across all weather scenarios (crop param bug)",
    "cassava":   "DVS median=1.55 at 240d, max=1.63 — too slow to approach maturity",
    "sugarcane": "393-day growing season, exceeds 240-day episode limit",
}

# ---------------------------------------------------------------------------
# Trait features used for selection
# ---------------------------------------------------------------------------
DEFAULT_TRAIT_SCHEMA = "traits_v1_23d"

SCHEMA_FEATURE_NAMES = {
    "traits_v1_23d": [
        "TBASEM", "TSUM_total", "IDSL", "RDMCR",
        "DEPNR", "AMAX", "FOTB_onset", "IAIRDU",
    ],
    "traits_v1_6d": [
        "season_urgency",
        "development_constraint",
        "water_priority",
        "nitrogen_priority",
        "phosphorus_priority",
        "potassium_priority",
    ],
}

SCHEMA_LABELS = {
    "traits_v1_23d": "8D selection subspace from the 23D crop card",
    "traits_v1_6d": "6D policy-facing trait schema",
}

# ---------------------------------------------------------------------------
# Per-crop geographic ranges for dataset generation
# ---------------------------------------------------------------------------
CROP_RANGES = {
    # ── Cool-adapted (TBASEM 0–3) ──
    "wheat":      {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "barley":     {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "fababean":   {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "rapeseed":   {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "potato":     {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "sugarbeet":  {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "seed_onion": {"latitude_range": [45.0, 55.0], "longitude_range": [-10.0, 30.0]},
    "sunflower":  {"latitude_range": [35.0, 45.0], "longitude_range": [-10.0, 30.0]},
    # ── Temperate-adapted (TBASEM 7–8) ──
    "soybean":    {"latitude_range": [38.0, 48.0], "longitude_range": [-100.0, 30.0]},
    "rice":       {"latitude_range": [25.0, 40.0], "longitude_range": [-10.0, 120.0]},
    # ── Warm-adapted (TBASEM 10–12) ──
    "maize":      {"latitude_range": [39.0, 49.0], "longitude_range": [-10.0, 30.0]},
    "sorghum":    {"latitude_range": [39.0, 49.0], "longitude_range": [-10.0, 30.0]},
    "millet":     {"latitude_range": [10.0, 45.0], "longitude_range": [-10.0, 80.0]},
    "cotton":     {"latitude_range": [25.0, 40.0], "longitude_range": [-100.0, 80.0]},
    "cowpea":     {"latitude_range": [8.0,  20.0], "longitude_range": [-10.0, 40.0]},
    "groundnut":  {"latitude_range": [15.0, 35.0], "longitude_range": [-10.0, 80.0]},
    "mungbean":   {"latitude_range": [15.0, 30.0], "longitude_range": [60.0,  100.0]},
    "pigeonpea":  {"latitude_range": [10.0, 25.0], "longitude_range": [60.0,  85.0]},
    "chickpea":   {"latitude_range": [20.0, 40.0], "longitude_range": [-10.0, 80.0]},
    "sweetpotato": {"latitude_range": [15.0, 35.0], "longitude_range": [-10.0, 120.0]},
}


# ═══════════════════════════════════════════════════════════════════════════
# Core logic
# ═══════════════════════════════════════════════════════════════════════════

def _resolve_traits_dir(traits_dir: Path, trait_schema: str) -> Path:
    """Resolve root crop_traits dir to a schema-specific directory when needed."""
    if traits_dir.name == trait_schema:
        return traits_dir
    if trait_schema == DEFAULT_TRAIT_SCHEMA:
        schema_dir = traits_dir / trait_schema
        return schema_dir if schema_dir.exists() else traits_dir
    return traits_dir / trait_schema


def load_crop_traits(traits_dir: Path, trait_schema: str) -> Dict[str, Dict[str, float]]:
    """Load crop trait JSON cards, returning {crop_name: {feature: value}}."""
    crops: Dict[str, Dict[str, float]] = {}
    resolved_traits_dir = _resolve_traits_dir(traits_dir, trait_schema)
    feature_names = SCHEMA_FEATURE_NAMES[trait_schema]

    for f in sorted(resolved_traits_dir.glob("*.json")):
        with open(f) as fh:
            card = json.load(fh)
        crop = card["crop"]
        if crop in EXCLUDED_CROPS:
            continue
        if trait_schema == "traits_v1_23d":
            core = card["core_facts"]
            fotb = core["assimilation_and_partition"]["FOTB_storage_onset_DVS"]
            if fotb is None:
                continue
            crops[crop] = {
                "TBASEM": core["temperature"]["TBASEM_C"],
                "TSUM_total": core["phenology"]["TSUM_total_Cd"],
                "IDSL": core["phenology"]["IDSL"],
                "RDMCR": core["root_and_water"]["RDMCR_cm"],
                "DEPNR": core["root_and_water"]["DEPNR"],
                "AMAX": core["assimilation_and_partition"]["AMAX_peak"],
                "FOTB_onset": fotb,
                "IAIRDU": core["root_and_water"]["IAIRDU"],
            }
            continue

        if trait_schema == "traits_v1_6d":
            source_facts = card.get("source_facts", {})
            fotb = source_facts.get("season_urgency", {}).get("FOTB_storage_onset_DVS")
            if fotb is None:
                continue
            decision_axes = card["core_facts"]["decision_axes"]
            crops[crop] = {name: float(decision_axes[name]) for name in feature_names}
            continue

        raise ValueError(f"Unsupported trait schema: {trait_schema}")
    return crops


def build_distance_matrix(
    crop_names: List[str],
    crops: Dict[str, Dict[str, float]],
    feature_names: List[str],
) -> Tuple[np.ndarray, np.ndarray]:
    """Min-max normalise traits and compute pairwise Euclidean distances."""
    raw = np.array(
        [[crops[c][f] for f in feature_names] for c in crop_names],
        dtype=np.float64,
    )
    mins = raw.min(axis=0)
    maxs = raw.max(axis=0)
    scales = maxs - mins
    scales[scales == 0] = 1.0
    normed = (raw - mins) / scales

    n = len(crop_names)
    dist = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            dist[i, j] = np.linalg.norm(normed[i] - normed[j])
    return normed, dist


def _volume_proxy(normed: np.ndarray, idxs: List[int]) -> float:
    """Product of per-feature ranges (proxy for hyper-rectangle volume)."""
    sub = normed[idxs]
    fr = sub.max(axis=0) - sub.min(axis=0)
    return float(np.prod(fr[fr > 0]))


def _min_pairwise(dist: np.ndarray, idxs: List[int]) -> float:
    """Minimum pairwise distance within a set of indices."""
    pairs = list(combinations(idxs, 2))
    if not pairs:
        return 0.0
    return min(dist[i, j] for i, j in pairs)


def select_fixed_ood(
    crop_names: List[str],
    normed: np.ndarray,
    dist: np.ndarray,
    n_ood: int = 4,
) -> Tuple[List[str], List[str]]:
    """Select the best fixed OOD set of size n_ood.

    Optimises a weighted combination of:
      - ID pool trait-space volume (higher = better; ID pool retains coverage)
      - OOD set spread (higher = better; OOD tests diverse directions)
    """
    n = len(crop_names)
    best_combo = None
    best_score = -1.0

    for ood_combo in combinations(range(n), n_ood):
        id_pool = [i for i in range(n) if i not in ood_combo]
        id_vol = _volume_proxy(normed, id_pool)
        ood_spread = _min_pairwise(dist, list(ood_combo))
        score = id_vol * 0.7 + ood_spread * 0.3
        if score > best_score:
            best_score = score
            best_combo = ood_combo

    ood_names = [crop_names[i] for i in best_combo]
    id_pool = [c for c in crop_names if c not in ood_names]
    return ood_names, id_pool


def select_best_k(
    pool_names: List[str],
    crop_names: List[str],
    dist: np.ndarray,
    k: int,
) -> List[str]:
    """Exhaustive search for the k-crop subset maximising min pairwise dist."""
    idx_map = {c: i for i, c in enumerate(crop_names)}
    pool_idxs = [idx_map[c] for c in pool_names]

    best_combo = None
    best_score = -1.0
    for combo in combinations(pool_idxs, k):
        md = _min_pairwise(dist, list(combo))
        if md > best_score:
            best_score = md
            best_combo = combo
    return [crop_names[i] for i in best_combo]


def greedy_maxmin_expand(
    seed_names: List[str],
    target_size: int,
    pool_names: List[str],
    crop_names: List[str],
    dist: np.ndarray,
) -> List[str]:
    """Greedily expand seed set within pool by max-min distance."""
    idx_map = {c: i for i, c in enumerate(crop_names)}
    pool_idxs = set(idx_map[c] for c in pool_names)
    selected = [idx_map[c] for c in seed_names]
    remaining = [i for i in pool_idxs if i not in selected]
    order = list(seed_names)

    while len(selected) < target_size and remaining:
        best_idx = max(remaining, key=lambda r: min(dist[r, s] for s in selected))
        selected.append(best_idx)
        remaining.remove(best_idx)
        order.append(crop_names[best_idx])
    return order


def coverage_metrics(
    selected: List[str],
    crop_names: List[str],
    normed: np.ndarray,
    dist: np.ndarray,
    feature_names: List[str],
) -> Dict[str, Any]:
    """Compute trait-space coverage statistics for a crop subset."""
    idx_map = {c: i for i, c in enumerate(crop_names)}
    idxs = [idx_map[c] for c in selected]
    sub = normed[idxs]

    feat_ranges = sub.max(axis=0) - sub.min(axis=0)
    pairs = list(combinations(idxs, 2))
    pair_dists = [dist[i, j] for i, j in pairs]

    min_d = np.min(pair_dists)
    min_pair = None
    for i, j in pairs:
        if dist[i, j] == min_d:
            min_pair = (crop_names[i], crop_names[j])
            break

    vol = float(np.prod(feat_ranges[feat_ranges > 0]))
    return {
        "avg_pairwise_dist": float(np.mean(pair_dists)),
        "min_pairwise_dist": float(min_d),
        "min_pair": min_pair,
        "volume_proxy": vol,
        "per_feature_range": {f: float(r) for f, r in zip(feature_names, feat_ranges)},
    }


def ood_distances(
    id_crops: List[str],
    ood_crops: List[str],
    crop_names: List[str],
    dist: np.ndarray,
) -> List[Dict[str, Any]]:
    """For each OOD crop, find its nearest ID crop and distance."""
    idx_map = {c: i for i, c in enumerate(crop_names)}
    result = []
    for oc in ood_crops:
        oi = idx_map[oc]
        nearest = min(id_crops, key=lambda c: dist[oi, idx_map[c]])
        d = dist[oi, idx_map[nearest]]
        result.append({"crop": oc, "nearest_id": nearest, "distance": float(d)})
    result.sort(key=lambda x: -x["distance"])
    return result


# ═══════════════════════════════════════════════════════════════════════════
# Display
# ═══════════════════════════════════════════════════════════════════════════

def _bucket_level(value: float) -> str:
    if value < 0.34:
        return "low"
    if value < 0.67:
        return "medium"
    return "high"


def _trait_notes_23d(d: Dict[str, float]) -> str:
    notes = []
    if d["TBASEM"] <= 3:    notes.append("cool")
    elif d["TBASEM"] <= 8:  notes.append("temperate")
    else:                   notes.append("warm")
    if d["TSUM_total"] >= 2300:   notes.append("long-season")
    elif d["TSUM_total"] >= 1700: notes.append("medium")
    else:                         notes.append("short")
    if d["RDMCR"] >= 150:  notes.append("deep-root")
    elif d["RDMCR"] < 80:  notes.append("shallow-root")
    if d["DEPNR"] <= 3.0:  notes.append("drought-sensitive")
    elif d["DEPNR"] >= 5.0: notes.append("very-tolerant")
    if d["AMAX"] >= 70:    notes.append("high-AMAX")
    elif d["AMAX"] <= 30:  notes.append("low-AMAX")
    if d["IDSL"] == 0:     notes.append("temp-only")
    elif d["IDSL"] == 2:   notes.append("vernalization")
    if d["IAIRDU"] == 1:   notes.append("air-ducts")
    if d["FOTB_onset"] <= 0.95:  notes.append("early-storage")
    elif d["FOTB_onset"] >= 1.4: notes.append("very-late-storage")
    return ", ".join(notes)


def _trait_notes_6d(d: Dict[str, float]) -> str:
    return ", ".join([
        f"season={_bucket_level(d['season_urgency'])}",
        f"dev={_bucket_level(d['development_constraint'])}",
        f"water={_bucket_level(d['water_priority'])}",
        f"N={_bucket_level(d['nitrogen_priority'])}",
        f"P={_bucket_level(d['phosphorus_priority'])}",
        f"K={_bucket_level(d['potassium_priority'])}",
    ])


def print_condition(
    label: str,
    id_crops: List[str],
    ood_crops: List[str],
    crops: Dict[str, Dict[str, float]],
    metrics: Dict[str, Any],
    ood_info: List[Dict[str, Any]],
    samples_per_crop: int,
    feature_names: List[str],
    trait_schema: str,
) -> None:
    print(f"\n{'─'*105}")
    print(f"  {label}  ({samples_per_crop} samples/crop, {len(id_crops)*samples_per_crop} total)")
    print(f"{'─'*105}")

    if trait_schema == "traits_v1_23d":
        print(f"  {'Crop':<14} {'TBASE':>5} {'TSUMt':>6} {'IDSL':>4} "
              f"{'RDMCR':>5} {'DEPNR':>5} {'AMAX':>5} {'FOTB':>5} {'AIR':>3}   Key direction")
        print(f"  {'-'*100}")
        for c in id_crops:
            d = crops[c]
            print(f"  {c:<14} {d['TBASEM']:>5.0f} {d['TSUM_total']:>6.0f} "
                  f"{d['IDSL']:>4.0f} {d['RDMCR']:>5.0f} {d['DEPNR']:>5.1f} "
                  f"{d['AMAX']:>5.0f} {d['FOTB_onset']:>5.2f} {d['IAIRDU']:>3.0f}   "
                  f"{_trait_notes_23d(d)}")
    else:
        header = f"  {'Crop':<14} {'Season':>6} {'Dev':>6} {'Water':>6} {'N':>6} {'P':>6} {'K':>6}   Key direction"
        print(header)
        print(f"  {'-' * (len(header) - 2)}")
        for c in id_crops:
            d = crops[c]
            print(
                f"  {c:<14} "
                f"{d['season_urgency']:>6.2f} "
                f"{d['development_constraint']:>6.2f} "
                f"{d['water_priority']:>6.2f} "
                f"{d['nitrogen_priority']:>6.2f} "
                f"{d['phosphorus_priority']:>6.2f} "
                f"{d['potassium_priority']:>6.2f}   "
                f"{_trait_notes_6d(d)}"
            )

    print(f"\n  Coverage: vol={metrics['volume_proxy']:.4f}  "
          f"avg_dist={metrics['avg_pairwise_dist']:.3f}  "
          f"min_dist={metrics['min_pairwise_dist']:.3f} "
          f"({metrics['min_pair'][0]}-{metrics['min_pair'][1]})")

    avg_ood = np.mean([o["distance"] for o in ood_info])
    print(f"  OOD avg distance: {avg_ood:.3f}")
    for o in ood_info:
        print(f"    {o['crop']:<14} -> {o['nearest_id']:<14} dist={o['distance']:.3f}")


# ═══════════════════════════════════════════════════════════════════════════
# Config generation
# ═══════════════════════════════════════════════════════════════════════════

def write_per_crop_weather_config(
    crop: str,
    num_train: int = 3200,
    num_val: int = 128,
    num_test: int = 512,
) -> Path:
    """Write a single-crop weather pool YAML config."""
    config = {
        "env_name": "wofost_gym",
        "env_id": "lnpkw-v0",
        "wofost_gym_path": "../AgriManagerExternal/WOFOSTGym",
        "save_folder": f"/tmp/wofost_configs_pool_crop_{crop}/",
        "data_mode": "multi_crop_ood",
        "train_crops": [crop],
        "eval_crops": [crop],
        "num_train_samples": num_train,
        "num_val_samples": num_val,
        "num_test_samples": num_test,
        "generation_seed": 42,
        "year_range": [1984, 2019],
        "min_dvs_threshold": 1.5,
        "crop_ranges": {crop: CROP_RANGES[crop]},
    }

    out_path = POOL_CONFIG_DIR / f"pool_crop_{crop}.yaml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)
    return out_path


# ═══════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Select ID/OOD crop splits by maximising trait-space coverage.",
    )
    parser.add_argument(
        "--traits-dir", type=str, default=None,
        help="Path to crop trait JSON directory",
    )
    parser.add_argument(
        "--trait-schema",
        type=str,
        default=DEFAULT_TRAIT_SCHEMA,
        choices=sorted(SCHEMA_FEATURE_NAMES.keys()),
        help="Trait schema to use for split selection.",
    )
    parser.add_argument(
        "--write-per-crop-configs", action="store_true",
        help=(
            "Write one weather-pool YAML config per usable crop to "
            "integrations/wofost_gym/dataset_tools/weather_pool_configs/."
        ),
    )
    args = parser.parse_args()

    traits_dir = Path(args.traits_dir) if args.traits_dir else DEFAULT_TRAITS_DIR
    trait_schema = args.trait_schema
    feature_names = SCHEMA_FEATURE_NAMES[trait_schema]
    resolved_traits_dir = _resolve_traits_dir(traits_dir, trait_schema)

    # ── Load and validate ──────────────────────────────────────────────────
    crops = load_crop_traits(traits_dir, trait_schema)
    crop_names = sorted(crops.keys())
    print(f"Usable crops: {len(crop_names)}")
    print(f"Trait schema: {trait_schema} ({SCHEMA_LABELS[trait_schema]})")
    print(f"Traits dir: {resolved_traits_dir}")
    print(f"Excluded: {list(EXCLUDED_CROPS.keys())}")
    for crop, reason in EXCLUDED_CROPS.items():
        print(f"  {crop}: {reason}")

    # ── Build distance matrix ──────────────────────────────────────────────
    normed, dist = build_distance_matrix(crop_names, crops, feature_names)

    # ── Step 1: Select fixed OOD set ───────────────────────────────────────
    print(f"\n{'='*105}")
    print("Step 1: Select fixed OOD evaluation set (4 crops)")
    print(f"{'='*105}")
    ood_names, id_pool = select_fixed_ood(crop_names, normed, dist, n_ood=4)
    print(f"  OOD set:  {ood_names}")
    print(f"  ID pool:  {id_pool} ({len(id_pool)} crops)")

    # ── Step 2: Select optimal ID sets from pool ───────────────────────────
    print(f"\n{'='*105}")
    print("Step 2: Select optimal ID sets from the 16-crop pool")
    print(f"{'='*105}")

    # 4-ID: exhaustive search
    id_4 = select_best_k(id_pool, crop_names, dist, k=4)
    # 8-ID: greedy expansion from optimal 4
    id_8 = greedy_maxmin_expand(id_4, 8, id_pool, crop_names, dist)
    # 16-ID: full pool
    id_16 = list(id_pool)

    # ── Metrics ────────────────────────────────────────────────────────────
    m4 = coverage_metrics(id_4, crop_names, normed, dist, feature_names)
    m8 = coverage_metrics(id_8, crop_names, normed, dist, feature_names)
    m16 = coverage_metrics(id_16, crop_names, normed, dist, feature_names)

    ood_d4 = ood_distances(id_4, ood_names, crop_names, dist)
    ood_d8 = ood_distances(id_8, ood_names, crop_names, dist)
    ood_d16 = ood_distances(id_16, ood_names, crop_names, dist)

    # ── Display ────────────────────────────────────────────────────────────
    print(f"\n{'='*105}")
    print("EXPERIMENTAL DESIGN: Crop Diversity Scaling")
    print(f"  Fixed training budget: 3200 episodes")
    print(f"  Selection traits:      {trait_schema} ({len(feature_names)}D)")
    print(f"  Fixed OOD eval set:    {ood_names}")
    print(f"{'='*105}")

    print_condition("4-ID", id_4, ood_names, crops, m4, ood_d4, 800, feature_names, trait_schema)
    print_condition("8-ID", id_8, ood_names, crops, m8, ood_d8, 400, feature_names, trait_schema)
    print_condition("16-ID", id_16, ood_names, crops, m16, ood_d16, 200, feature_names, trait_schema)

    # ── Per-feature coverage comparison ────────────────────────────────────
    print(f"\n{'='*105}")
    print("PER-FEATURE COVERAGE COMPARISON")
    print(f"{'='*105}")
    idx_map = {c: i for i, c in enumerate(crop_names)}
    print(f"  {'Feature':<12} {'4-ID':>6} {'8-ID':>6} {'16-ID':>6}")
    print(f"  {'-'*35}")
    for fi, fn in enumerate(feature_names):
        vals = []
        for id_list in [id_4, id_8, id_16]:
            idxs = [idx_map[c] for c in id_list]
            sub = normed[idxs]
            r = sub[:, fi].max() - sub[:, fi].min()
            vals.append(r)
        print(f"  {fn:<12} {vals[0]:>6.2f} {vals[1]:>6.2f} {vals[2]:>6.2f}")

    # ── Write configs ──────────────────────────────────────────────────────
    if args.write_per_crop_configs:
        paths = [write_per_crop_weather_config(crop) for crop in crop_names]
        print(f"\nPer-crop weather configs written:")
        for path in paths:
            print(f"  {path}")


if __name__ == "__main__":
    main()
