env_name: cycles_gym
dataset_id: cycles_gym_smoke_nn

base_config:
  env_id: CornShortRockSpringsFW-v1
  cycles_gym_path: ../AgriManagerExternal/CyclesGym
  llm_mode: false
  turn_num: 8
  env_kwargs:
    delta: 7
    n_actions: 11
    maxN: 150
    start_year: 1980
    end_year: 1980

train_configs:
  - seed: 0
  - seed: 1
  - seed: 2
  - seed: 3
  - seed: 4
  - seed: 5
  - seed: 6
  - seed: 7
  - seed: 8
  - seed: 9
  - seed: 10
  - seed: 11
  - seed: 12
  - seed: 13
  - seed: 14
  - seed: 15
  - seed: 16
  - seed: 17
  - seed: 18
  - seed: 19
  - seed: 20
  - seed: 21
  - seed: 22
  - seed: 23
  - seed: 24
  - seed: 25
  - seed: 26
  - seed: 27
  - seed: 28
  - seed: 29
  - seed: 30
  - seed: 31

val_configs:
  - seed: 90
  - seed: 91
  - seed: 92
  - seed: 93
  - seed: 94
  - seed: 95
  - seed: 96
  - seed: 97

test_configs:
  - seed: 100
  - seed: 101
  - seed: 102
  - seed: 103
  - seed: 104
  - seed: 105
  - seed: 106
  - seed: 107
