model_provider: "vllm_offline"
model_name: "Qwen/Qwen3-30B-A3B-Instruct-2507"

tensor_parallel_size: 2
gpu_memory_utilization: 0.9
trust_remote_code: true
dtype: "bfloat16"
tokenizer_mode: "auto"
max_model_len: 8000
